# Generated by Django 6.1.1 on 2026-10-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_workspacemembership_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspacemembership',
            options={'ordering': ['joined_at']},
        ),
        migrations.AlterField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('member', 'Участник'), ('manager', 'Менеджер')], default='member', max_length=20),
        ),
    ]
