# Generated by Django 6.1.1 on 2026-10-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_workspacemembership_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
    ]
