# Generated by Django 6.1.1 on 2026-10-10 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_task_attachment_task_visibility_taskgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='visible_to_users',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, которые видят задачу при visibility=users', related_name='visible_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='visibility',
            field=models.CharField(choices=[('public', 'Все участники пространства'), ('private', 'Только автор и исполнитель'), ('users', 'Только выбранные пользователи'), ('group', 'Только участники группы')], default='public', max_length=10),
        ),
    ]
